global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gitflow-backend'
    static_configs:
      - targets: ['backend:3001']

  - job_name: 'gitflow-ml'
    static_configs:
      - targets: ['ml-pipeline:5000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
